# Use "python language" so that the C compiler can be chosen in env
language: python
python:
  - "3.6"

# Use Ubuntu 12.04 with container infrastructure so long as wine fails to install in 14.04
dist: precise
sudo: false

env:
  # gcc without MinGW
  - CC=gcc WINCC=false WITH_KERN=true
  - CC="gcc -m32" WINCC=false
  # clang without MinGW
  - CC=clang WINCC=false
  - CC="clang -m32" WINCC=false
  # MinGW compilation
  - OS=Windows_NT WINCC=x86_64-w64-mingw32-gcc CC=$WINCC
  - OS=Windows_NT WINCC=i686-w64-mingw32-gcc CC=$WINCC
  # MinGW compilation with ANSI function instead of the wide-character ones
  - OS=Windows_NT WINCC=x86_64-w64-mingw32-gcc CC=$WINCC HAVE_UNICODE=n
  - OS=Windows_NT WINCC=i686-w64-mingw32-gcc CC=$WINCC HAVE_UNICODE=n

addons:
  apt:
    packages:
    - gcc-multilib
    - gdb
    - libc6-dev-i386
    - libgmp-dev
    - libgtk-3-dev
    - libmnl-dev
    - linux-headers-generic
    - libpulse-dev
    #- libsdl2-dev # Unavailable in Ubuntu 12.04
    - binutils-mingw-w64
    - gcc-mingw-w64
    - wine

install:
  # pip does not behave properly when CC is somewhat weird
  - if [ "$CC" = "gcc" ] ; then pip install cffi numpy ; fi

before_script:
# Find the version of the installed kernel headers from linux-headers-generic package
# Note: Travis-ci does not like having a colon after "Depends" in the regex :(
  - if "${WITH_KERN:-false}" ; then
    export KERNELVER="$(LANG=C dpkg --status linux-headers-generic |
        sed -n 's/^Depends. linux-headers-\(.*\)/\1/p')" ;
    fi

script:
# When building 32-bit programs, do not use the 64-bit installed libraries
  - if [ "${CC%m32}" = "$CC" ] ; then make test ;
    else make test PKG_CONFIG=false ;
    fi
  - make list-nobuild

# Do not spam by email so long as the build succeeds
notifications:
  email:
    on_success: never
